#!/bin/bash
# This script can be used to install Consul and its dependencies. This script has been tested with the following
# operating systems:
#
# - Ubuntu 16.04

set -e

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Include general-purpose bash functions from https://github.com/gruntwork-io/bash-commons. Assumes these were installed
# separately from this script, for example, using "cd /opt/gruntwork && git clone https://github.com/gruntwork-io/bash-commons".
source "/opt/gruntwork/bash-commons/assert.sh"
source "/opt/gruntwork/bash-commons/log.sh"

readonly DEFAULT_INSTALL_PATH="/opt/image-service"
readonly DEFAULT_CONSUL_USER="cat-image"
readonly SYSTEM_BIN_DIR="/usr/local/bin"

readonly SUPERVISOR_DIR="/etc/supervisor"
readonly SUPERVISOR_CONF_DIR="$SUPERVISOR_DIR/conf.d"

readonly SCRIPT_NAME="$(basename "$0")"

function print_usage {
  echo
  echo "Usage: install-image-service [OPTIONS]"
  echo
  echo "This script can be used to install Consul and its dependencies. This script has been tested with Ubuntu 16.04."
  echo
  echo "Required Arguments:"
  echo
  echo -e "  --version\t\tThe version of Consul to install. Do not include a \"v\" in the version number"
  echo
  echo "Optional Arguments:"
  echo
  echo -e "  --path\t\tThe path where Consul should be installed. Optional. Default: $DEFAULT_INSTALL_PATH."
  echo -e "  --user\t\tThe user who will own the Consul install directories. Optional. Default: $DEFAULT_CONSUL_USER."
  echo
  echo "Example:"
  echo
  echo "  install-consul --version 1.1.0"
}

# Install steps are based on: http://unix.stackexchange.com/a/291098/215969
function install_supervisord_debian {
  sudo apt-get install -y supervisor
  sudo update-rc.d supervisor defaults

  create_supervisor_config
  sudo systemctl enable supervisor
}

function create_supervisor_config {
  sudo mkdir -p "$SUPERVISOR_CONF_DIR"
  sudo cp "$SCRIPT_DIR/supervisord.conf" "$SUPERVISOR_DIR/supervisord.conf"
}

function has_yum {
  [ -n "$(command -v yum)" ]
}

function has_apt_get {
  [ -n "$(command -v apt-get)" ]
}

function install_dependencies {
  log_info "Installing dependencies"

  if $(has_apt_get); then
    sudo apt-get update -y
    sudo apt-get install -y curl unzip jq
    install_supervisord_debian
  else
    log_error "Could not find apt-get or yum. Cannot install dependencies on this OS."
    exit 1
  fi
}

function user_exists {
  local -r username="$1"
  id "$username" >/dev/null 2>&1
}

function create_image_service_user {
  local -r username="$1"

  if $(user_exists "$username"); then
    echo "User $username already exists. Will not create again."
  else
    log_info "Creating user named $username"
    sudo useradd --create-home "$username"
  fi
}

function create_image_service_install_paths {
  local -r path="$1"
  local -r username="$2"

  log_info "Creating install dirs for Consul at $path"
  sudo mkdir -p "$path"
  sudo mkdir -p "$path/bin"
  sudo mkdir -p "$path/config"
  sudo mkdir -p "$path/data"
  sudo mkdir -p "$path/log"

  log_info "Changing ownership of $path to $username"
  sudo chown -R "$username:$username" "$path"
}

function install_binaries {
  local -r path="$2"
  local -r username="$3"

  local -r url="https://github.com/anners/image-search.git"
  local -r download_path="/usr/local/src/image-service"
  local -r bin_dir="$path/bin"
  local -r image_service_dest_path="$bin_dir/image-service"
 # local -r run_consul_dest_path="$bin_dir/run-consul"

  log_info "Grabbing a copy of the image service from $url to $download_path"
  git clone "$url" "$download_path"

  cd "$download_path" ; go build

  log_info "Moving image-service binary to $image_service_dest_path"
  sudo mv "$download_path/image-service" "$image_service_dest_path"
  sudo chown "$username:$username" "$image_service_dest_path"
  sudo chmod a+x "$image_service_dest_path"

  local -r symlink_path="$SYSTEM_BIN_DIR/image-service"
  if [[ -f "$symlink_path" ]]; then
    log_info "Symlink $symlink_path already exists. Will not add again."
  else
    log_info "Adding symlink to $consul_dest_path in $symlink_path"
    sudo ln -s "$consul_dest_path" "$symlink_path"
  fi

  log_info "Copying Image run script to $run_image_service_dest_path"
  sudo cp "$SCRIPT_DIR/../run-image_service/run-image_service" "$run_image_service_dest_path"
  sudo chown "$username:$username" "$run_image_service_dest_path"
  sudo chmod a+x "$run_image_service_dest_path"
}

function install {
  local path="$DEFAULT_INSTALL_PATH"
  local user="$DEFAULT_IMAGE_SERVICE_USER"

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --path)
        path="$2"
        shift
        ;;
      --user)
        user="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_not_empty "--path" "$path"
  assert_not_empty "--user" "$user"

  log_info "Starting Image Service install"

  install_dependencies
  create_image_service_user "$user"
  create_image_service_install_paths "$path" "$user"
  install_binaries "$path" "$user"

  log_info "Consul install complete!"
}

install "$@"
